WIP-still have one test to go
amgoodman5/g59-array-warmup pull request #11
Opened 2017-10-11 20:01 UTC by quintanamiriam

WIP

2017-10-24 23:26 UTC, amgoodman5 requested changes

2017-10-24 23:26 UTC, amgoodman5 commented on filter/index.js
> +    return n % 2 === 0;
Excellent Job!  you can even refactor it further in es6
```js
const onlyEven = (array) => array.filter(n => n % 2 === 0 )
```

2017-10-24 23:26 UTC, amgoodman5 commented on map/index.js
> +    return array * 10;
Keep going! I would working on getting rid of the anonymous function before array and using the fat arrow syntax, also when you use map make sure you variable has a different name then the original array.  
```js
const multiplyBy10 = (array) => array.map(n => n * 10 )
```

2017-11-22 01:18 UTC, coloradokim commented
👍  All your tests are passing, so you’ve got a 3 on the standards `Define and call higher order functions` and `Refactor loops to use functional style`. Woo!

2017-11-22 01:18 UTC, closed without merging