First commit
amgoodman5/g59-array-warmup pull request #12
Opened 2017-10-11 20:04 UTC by SadatheToure

First commit

2017-10-24 23:01 UTC, amgoodman5 approved these changes

2017-10-24 23:01 UTC, amgoodman5 commented on map/index.js
> + return array.map(x => x * 10);
Excellent! nice job! 👍

2017-10-24 23:08 UTC, amgoodman5 requested changes

2017-10-24 23:08 UTC, amgoodman5 commented on map/index.js
>  function onlyVowels(array) {
Finish these :) it is super important that you at least understand how map and filter functions work and be refactored into your code!
``` 
function onlyVowels(array) {
return array.map(word => word.replace(/[^aeiou]*/gi, ''));
}
```

2017-11-22 01:23 UTC, coloradokim commented
![image](https://user-images.githubusercontent.com/10536053/33105153-0acbd256-cee9-11e7-8a17-b9e47d2c0118.png)

You have 4/6 tests passing. Since you were able to get one of the ‘filter’ functions to work, you’re all set and you now have a 3 on the standards `Define and call higher order functions` and `Refactor loops to use functional style.`

2017-11-22 01:23 UTC, closed without merging