not done
amgoodman5/g59-array-warmup pull request #13
Opened 2017-10-11 20:12 UTC by crazymaster49

2017-10-24 22:46 UTC, amgoodman5 requested changes

2017-10-24 22:46 UTC, amgoodman5 commented on map/index.js
> +  return array.map(n => n * 10)
Try something like this!
``` 
const multiplyBy10 = (array) => array.map(num => num * 10)
```

2017-10-24 22:51 UTC, amgoodman5 requested changes

2017-10-24 22:51 UTC, amgoodman5 commented on filter/index.js
> +  //where are the snacks? With sam
Finish this! 🔢

2017-11-22 01:24 UTC, coloradokim commented
All your tests are passing, so you’ve got a 3 on the standards `Define and call higher order functions` and `Refactor loops to use functional style`. Woo!

2017-11-22 01:24 UTC, closed without merging