for my fork
amgoodman5/g59-array-warmup pull request #15
Opened 2017-10-11 20:22 UTC by eddycaldas

2017-10-24 21:38 UTC, amgoodman5 approved these changes

2017-10-24 21:38 UTC, amgoodman5 commented on map/index.js
> +}
Awesome job! This is a correct use of how to use map 👍

2017-10-24 21:42 UTC, amgoodman5 requested changes

2017-10-24 21:42 UTC, amgoodman5 commented on map/index.js
>    for (var i = 0; i < array.length; i++) {
Try this you can do it!

2017-11-22 01:28 UTC, coloradokim commented
![image](https://user-images.githubusercontent.com/10536053/33105304-ba74e030-cee9-11e7-9c7d-36d9ed2106b4.png)


You have 4/6 tests passing. Since you were able to get one of the ‘filter’ functions to work, you’re all set and you now have a 3 on the standards `Define and call higher order functions` and `Refactor loops to use functional style.`

2017-11-22 01:28 UTC, closed without merging