commit from Josh
amgoodman5/g59-array-warmup pull request #7
Opened 2017-10-11 19:55 UTC by joshnsaunders

still a work in progress

2017-10-24 23:31 UTC, amgoodman5 approved these changes

2017-10-24 23:31 UTC, amgoodman5 commented on filter/index.js
> +return  array.filter(x => x%2===0)
Nice! 👍

2017-10-24 23:38 UTC, amgoodman5 requested changes

2017-10-24 23:38 UTC, amgoodman5 commented on filter/index.js
> +return array.filter(x => x.some(y => y < 0)===false)
Wow! kudos! putting the false at the end buries the lead, declare a falsy statement initially`!` to give the reader an idea of whats going on in the code.

```js
return array.filter(x => !x.some(y => y < 0))
```

2017-11-21 17:51 UTC, coloradokim commented
Hi! I just looked through your pull request on the g59-array-warmup repo. All your tests are passing, so you’ve got a 3 on the standards `Define and call higher order functions` and `Refactor loops to use functional style`. Woo!

2017-11-22 01:08 UTC, closed without merging